### ISSUE TITLE
Android studio DevEco 中远程真机无法正常操作

### ISSUE THREAD

**Issue by yizems** [HuaweiOpenlab/SmartPhoto#2]
系统信息:WIN10 ,高分屏,XPS15,15寸 1080P

十分怀疑是高分屏的问题,滑动是有反应的,但是点击完全没有反应

![image](https://user-images.githubusercontent.com/16949474/47946687-05a3e080-df4a-11e8-87ea-38a63d298a3a.png)

这些点击都没有反应

**Comment by yangzhuo** [comment]
可以升级到最新版本试下（V1.2.5）

**Comment by yizems** [comment]
3Q 已经可以了
